INSERT INTO fuseauhoraire (id,pays_id,fuseau, utc, nom_en, nom_fr) VALUES
(1,1,    'Africa/Johannesburg',                'UTC-5',     'Cape Town, Durban, Johannesburg, Soweto, Pretoria','Le Cap, Durban, Johannesburg, Soweto, Pretoria'),
(2,2,    'Africa/Algiers',                     'UTC+1',     'Algiers, Boumerdas, Oran, Tébessa, Constantine','Alger, Boumerdas, Oran, Tébessa, Constantine'),
(3,3,    'Africa/Luanda',                      'UTC+1',     'Luanda, N’dalatando, Huambo, Lobito, Benguela'),
(4,4,    'Africa/Porto-Novo',                  'UTC+1',     'Cotonou, Abomey-Calavi, Djougou, Porto-Novo, Parakou'),
(5,5,    'Africa/Gaborone',                    'UTC+2',     'Gaborone, Francistown, Molepolole, Selebi-Phikwe, Maun'),
(6,6,    'Africa/Ouagadougou',                 'UTC+0',     'Ouagadougou, Bobo-Dioulasso, Koudougou, Ouahigouya, Banfora'),
(7,7,    'Africa/Bujumbura',                   'UTC+2',     'Bujumbura, Muyinga, Ruyigi, Gitega, Ngozi'),
(8,8,    'Africa/Douala',                      'UTC+1',     'Douala, Yaoundé, Garoua, Kousséri, Bamenda'),
(9,9,    'Atlantic/Cape_Verde',                'UTC-1',     'Praia, Mindelo, Santa Maria, Cova Figueira, Santa Cruz'),
(10,10,  'Africa/Bangui',                      'UTC+1',     'Bangui, Bimbo, Mbaïki, Berbérati, Kaga Bandoro'),
(11,11,  'Indian/Comoro',                      'UTC+3',     'Moroni, Moutsamoudou, Fomboni, Domoni, Adda-Douéni'),
(12,12,  'Africa/Brazzaville',                 'UTC+1',     'Brazzaville, Pointe-Noire, Dolisie, Kayes, Owando'),
(13,13,  'Africa/Kinshasa',                    'UTC+1',     'Kinshasa, Masina, Kikwit, Mbandaka, Matadi'),
(14,14,  'Africa/Abidjan',                     'UTC+0',     'Abidjan, Abobo, Bouaké, Daloa, San-Pédro'),
(15,15,  'Africa/Djibouti',                    'UTC+3',     'Djibouti, Ḏânan, Ali Sabieh, Tadjoura, Obock'),
(16,16,  'Africa/Cairo',                       'UTC+2',     'Cairo, Alexandria, Al Jīzah, Port Said, Suez'),
(17,17,  'Africa/Asmara',                      'UTC+3',     'Asmara, Keren, Massawa, Assab, Mendefera'),
(18,18,  'Africa/Addis_Ababa',                 'UTC+3',     'Addis Ababa, Dire Dawa, Mekele, Nazrēt, Bahir Dar'),
(19,19,  'Africa/Libreville',                  'UTC+1',     'Libreville, Port-Gentil, Franceville, Oyem, Moanda'),
(20,20,  'Africa/Banjul',                      'UTC+0',     'Brikama, Bakau, Banjul, Farafenni, Lamin'),
(21,21,  'Africa/Accra',                       'UTC+0',     'Accra, Kumasi, Tamale, Takoradi, Achiaman'),
(22,22,  'Africa/Conakry',                     'UTC+0',     'Camayenne, Conakry, Nzérékoré, Kindia, Kankan'),
(23,23,  'Africa/Bissau',                      'UTC+0',     'Bissau, Bafatá, Gabú, Bissorã, Bolama'),
(24,24,  'Africa/Malabo',                      'UTC+1',     'Bata, Malabo, Ebebiyin, Aconibe, Añisoc'),
(25,25,  'Africa/Nairobi',                     'UTC+3',     'Nairobi, Mombasa, Nakuru, Eldoret, Kisumu'),
(26,26,  'Africa/Maseru',                      'UTC+2',     'Maseru, Mafeteng, Leribe, Maputsoe, Mohale’s Hoek'),
(27,27,  'Africa/Monrovia',                    'UTC+0',     'Monrovia, Gbarnga, Kakata, Bensonville, Harper'),
(28,28,  'Africa/Tripoli',                     'UTC+2',     'Tripoli, Benghazi, Mişrātah, Tarhuna, Al Khums'),
(29,29,  'Indian/Antananarivo',                'UTC+3'      'Antananarivo, Toamasina, Antsirabe, Fianarantsoa, Mahajanga'),
(30,30,  'Africa/Blantyre',                    'UTC+2',     'Lilongwe, Blantyre, Mzuzu, Zomba, Kasungu'),
(31,31,  'Africa/Bamako',                      'UTC+0',     'Bamako, Sikasso, Mopti, Koutiala, Ségou'),
(32,32,  'Africa/Casablanca',                  'UTC+1',     'Casablanca, Rabat, Fes, Sale, Marrakesh'),
(33,33,  'Indian/Mauritius',                   'UTC+4',     'Port Louis, Vacoas, Curepipe, Quatre Bornes, Triolet'),
(34,34,  'Africa/Nouakchott',                  'UTC+0',     'Nouakchott, Nouâdhibou, Néma, Kaédi, Rosso'),
(35,35,  'Africa/Maputo',                      'UTC+2',     'Maputo, Matola, Beira, Nampula, Chimoio'),
(36,36,  'Africa/Windhoek',                    'UTC+2',     'Windhoek, Rundu, Walvis Bay, Oshakati, Swakopmund'),
(37,37,  'Africa/Niamey',                      'UTC+1',     'Niamey, Zinder, Maradi, Agadez, Alaghsas'),
(38,38,  'Africa/Lagos',                       'UTC+1',     'Lagos, Kano, Ibadan, Kaduna, Port Harcourt'),
(39,39,  'Africa/Kampala',                     'UTC+3',     'Kampala, Gulu, Lira, Mbarara, Jinja'),
(40,40,  'Africa/Kigali',                      'UTC+2',     'Kigali, Butare, Gitarama, Musanze, Gisenyi'),
(41,41,  'Africa/El_Aaiun',                    'UTC+1',     'Dakhla, Smara, Laayoune Plage'),
(42,42,  'Africa/Sao_Tome',                    'UTC+1',     'São Tomé, Santo António'),
(43,43,  'Africa/Dakar',                       'UTC+0',     'Dakar, Pikine, Touba, Thiès Nones, Saint-Louis'),
(44,44,  'Indian/Mahe',                        'UTC+4',     'Victoria, Anse Boileau, Bel Ombre, Beau Vallon, Cascade'),
(45,45,  'Africa/Freetown',                    'UTC+0',     'Freetown, Bo, Kenema, Koidu, Makeni'),
(46,46,  'Africa/Mogadishu',                   'UTC+3',     'Mogadishu, Hargeysa, Berbera, Kismayo, Marka'),
(47,47,  'Africa/Khartoum',                    'UTC+2',     'Khartoum, Omdurman, Port Sudan, Kassala, El Obeid'),
(48,48,  'Africa/Juba',                        'UTC+3',     'Juba, Malakal, Wau, Pajok, Yei'),
(49,49,  'Africa/Mbabane',                     'UTC+2',     'Manzini, Mbabane, Big Bend, Malkerns, Mhlume'),
(50,50,  'Africa/Dar_es_Salaam',               'UTC+3',     'Dar es Salaam, Mwanza, Zanzibar, Arusha, Mbeya'),
(51,51,  'Africa/Ndjamena',                    'UTC+1',     'N''Djamena, Moundou, Sagh, Abéché, Kelo'),
(52,52,  'Africa/Lome',                        'UTC+0',     'Lomé, Sokodé, Kara, Atakpamé, Kpalimé'),
(53,53,  'Africa/Tunis',                       'UTC+1',     'Tunis, Sfax, Sousse, Midoun, Kairouan'),
(54,54,  'Africa/Lusaka',                      'UTC+2',     'Lusaka, Kitwe, Ndola, Kabwe, Chingola'),
(55,55,  'Africa/Harare',                      'UTC+2',     'Harare, Bulawayo, Chitungwiza, Mutare, Gweru'),

(56,56,  'America/Antigua',                    'UTC+4',     'Saint John’s, Piggotts, Bolands, Codrington, Parham'),
(57,57,  'America/Argentina/Buenos_Aires',     'UTC+3',     'Buenos Aires, La Plata, Mar del Plata, Quilmes, Morón'),
(58,57,  'America/Argentina/Catamarca',        'UTC+3',     'San Fernando del Valle de Catamarca, Comodoro Rivadavia, Trelew, Puerto Madryn, Esquel'),
(59,57,  'America/Argentina/Cordoba',          'UTC+3',     'Córdoba, Rosario, Santa Fe de la Vera Cruz, Resistencia, Santiago del Estero'),
(60,57,  'America/Argentina/Jujuy',            'UTC+3',     'San Salvador de Jujuy, San Pedro, Libertador General San Martín, Palpalá, La Quiaca'),
(61,57,  'America/Argentina/La_Rioja',         'UTC+3',     'La Rioja, Chilecito, Arauco, Chamical'),
(62,57,  'America/Argentina/Mendoza',          'UTC+3',     'Mendoza, San Rafael, San Martín'),
(63,57,  'America/Argentina/Rio_Gallegos',     'UTC+3',     'Río Gallegos, Caleta Olivia, Pico Truncado, Puerto Deseado, Las Heras'),
(64,57,  'America/Argentina/Salta',            'UTC+3',     'Salta, Neuquén, Santa Rosa, San Carlos de Bariloche, Cipolletti'),
(65,57,  'America/Argentina/San_Juan',         'UTC+3',     'San Juan, Chimbas, Santa Lucía, Pocito, Caucete'),
(66,57,  'America/Argentina/San_Luis',         'UTC+3',     'San Luis, Villa Mercedes, La Punta, Merlo, Justo Daract'),
(67,57,  'America/Argentina/Tucuman',          'UTC+3',     'San Miguel de Tucumán, Yerba Buena, Tafí Viejo, Alderetes, Aguilares'),
(68,57,  'America/Argentina/Ushuaia',          'UTC+3',     'Ushuaia'),
(69,58,  'America/Nassau',                     'UTC-5',     'Nassau, Lucaya, Freeport, West End, Cooper’s Town'),
(70,59,  'America/Barbados',                   'UTC-4',     'Bridgetown, Speightstown, Oistins, Bathsheba, Holetown'),
(71,60,  'America/Belize',                     'UTC-6',     'Belize City, San Ignacio, Orange Walk, Belmopan, Dangriga'),
(72,61,  'America/La_Paz',                     'UTC-4',     'Santa Cruz de la Sierra, Cochabamba, La Paz, Sucre, Oruro'),
(73,62,  'America/Eirunepe',                   'UTC-5',     'Eirunepé, Benjamin Constant, Envira'),
(74,63,  'America/Dawson',                     'UTC-8',     'Dawson'),
(75,63,  'America/Vancouver',                  'UTC-8',     'Vancouver, Surrey, Okanagan, Victoria, Burnaby'),
(76,63,  'America/Whitehorse',                 'UTC-8',     'Whitehorse'),
(77,63,  'America/Cambridge_Bay',              'UTC-7',     'Cambridge Bay'),
(78,63,  'America/Creston',                    'UTC-7',     'Creston'),
(79,63,  'America/Dawson_Creek',               'UTC-7',     'Fort St. John, Dawson Creek'),
(80,63,  'America/Edmonton',                   'UTC-7',     'Calgary, Edmonton, Fort McMurray, Red Deer, Lethbridge'),
(81,63,  'America/Fort_Nelson',                'UTC-7',     'Fort_Nelson'),
(82,63,  'America/Inuvik',                     'UTC-7',     'Inuvik'),
(83,63,  'America/Yellowknife',                'UTC-7',     'Yellowknife'),
(84,63,  'America/Rainy_River',                'UTC-6',     'Rainy River'),
(85,63,  'America/Rankin_Inlet',               'UTC-6',     'Rankin Inlet'),
(86,63,  'America/Regina',                     'UTC-6',     'Saskatoon, Regina, Prince Albert, Moose Jaw, North Battleford'),
(87,63,  'America/Resolute',                   'UTC-6',     'Resolute'),
(88,63,  'America/Swift_Current',              'UTC-6',     'Swift Current'),
(89,63,  'America/Winnipeg',                   'UTC-6',     'Winnipeg, Brandon, Portage la Prairie, Thompson, Selkirk'),
(90,63,  'America/Atikokan',                   'UTC-5',     'Atikokan'),
(91,63,  'America/Iqaluit',                    'UTC-5',     'Iqaluit'),
(92,63,  'America/Nipigon',                    'UTC-5',     'Nipigon'),
(93,63,  'America/Pangnirtung',                'UTC-5',     'Pangnirtung'),
(94,63,  'America/Thunder_Bay',                'UTC-5',     'Thunder Bay'),
(95,63,  'America/Toronto',                    'UTC-5',     'Toronto, Montréal, Ottawa, Mississauga, North York'),
(96,63,  'America/Blanc-Sablon',               'UTC-4',     'Lévis'),
(97,63,  'America/Glace_Bay',                  'UTC-4',     'Sydney, Glace Bay, Sydney Mines'),
(98,63,  'America/Goose_Bay',                  'UTC-4',     'Labrador City, Happy Valley-Goose Bay'),
(99,63,  'America/Halifax',                    'UTC-4',     'Halifax, Dartmouth, Charlottetown, Lower Sacvkille, Truro, Sydney Mines'),
(100,63,  'America/Moncton',                   'UTC-4',     'Saint John, Moncton, Fredericton, Dieppe, Miramichi'),
(101,63,  'America/St_Johns',                  'UTC-3:30',  'St. John''s, Mount Pearl, Corner Brook, Conception Bay South, Bay Roberts'),
(102,64,  'Pacific/Easter',                    'UTC-6',     'Easter'),
(103,64,  'America/Santiago',                  'UTC-4',     'Santiago, Puente Alto, Antofagasta, Viña del Mar, Valparaíso'),
(104,64,  'America/Punta_Arenas',              'UTC-3',     'Punta Arenas'),
(105,65,  'America/Bogota',                    'UTC-5',     'Bogotá, Cali, Medellín, Barranquilla, Cartagena'),
(106,66,  'America/Costa_Rica',                'UTC-6',     'San José, Limón, San Francisco, Alajuela, Liberia'),
(107,67,  'America/Havana',                    'UTC-5',     'Havana, Santiago de Cuba, Camagüey, Holguín, Guantánamo'),
(108,68,  'America/Santo_Domingo',             'UTC-4',     'Santo Domingo, Santiago de los Caballeros, Santo Domingo Oeste, San Pedro de Macorís, La Romana'),
(109,69,  'America/Dominica',                  'UTC-4',     'Roseau, Portsmouth, Berekua, Saint Joseph, Wesley'),
(110,70,  'Pacific/Galapagos',                 'UTC-4',     'Puerto Ayora, Puerto Baquerizo Moreno'),
(111,70,  'America/Guayaquil',                 'UTC-4',     'Guayaquil, Quito, Cuenca, Santo Domingo de los Colorados, Machala'),
(112,71,  'America/Adak',                      'UTC-10',    'Adak'),
(113,71,  'Pacific/Honolulu',                  'UTC-10',    'Honolulu, Pearl City, Hilo, Kailua, Waipahu'),
(114,71,  'America/Anchorage',                 'UTC-10',    'Anchorage, Fairbanks, Eagle River, Badger, Knik-Fairview'),
(115,71,  'America/Juneau',                    'UTC-9',    'Juneau'),
(116,71,  'America/Metlakatla',                'UTC-9',    'Metlakatla'),
(117,71,  'America/Nome',                      'UTC-9',    'Nome'),
(118,71,  'America/Sitka',                     'UTC-9',    'Sitka, Ketchikan'),
(119,71,  'America/Yakutat',                   'UTC-9',    'Yakutat'),
(120,71,  'America/Los_Angeles',               'UTC-8',    'Los Angeles, San Diego, San Jose, San Francisco, Seattle'),
(121,71,  'America/Boise',                     'UTC-8',    'Boise, Nampa, Meridian, Idaho Falls, Pocatello'),
(122,71,  'America/Denver',                    'UTC-7',    'El Paso, Denver, Albuquerque, Colorado Springs, Aurora'),
(123,71,  'America/Phoenix',                   'UTC-7',    'Phoenix, Tucson, Mesa, Chandler, Glendale'),
(124,71,  'America/Chicago',                   'UTC-6',    'Chicago, Houston, San Antonio, Dallas, Austin'),
(125,71,  'America/Indiana/Knox',              'UTC-6',    'Knos'),
(126,71,  'America/Indiana/Tell_City',         'UTC-6',    'Tell City'),
(127,71,  'America/Menominee',                 'UTC-6',    'Menominee, Iron Mountain, Ironwood, Kingsford, Iron River'),
(128,71,  'America/North_Dakota/Beulah',       'UTC-6',    'Beulah'),
(129,71,  'America/North_Dakota/Center',       'UTC-6',    'North Dakota center'),
(130,71,  'America/North_Dakota/New_Salem',    'UTC-6',    'New Salem, Mandan'),
(131,71,  'America/Detroit',                   'UTC-5',    'Detroit, Grand Rapids, Warren, Sterling Heights, Lansing'),
(132,71,  'America/Indiana/Indianapolis',      'UTC-5',    'Indianapolis, Fort Wayne, South Bend, Bloomington, Carmel'),
(133,71,  'America/Indiana/Marengo',           'UTC-5',    'Marengo'),
(134,71,  'America/Indiana/Petersburg',        'UTC-5',    'Petersburg'),
(135,71,  'America/Indiana/Vevay',             'UTC-5',    'Vevay'),
(136,71,  'America/Indiana/Vincennes',         'UTC-5',    'Vincennes, Jasper, Washington, Huntingburg'),
(137,71,  'America/Indiana/Winamac',           'UTC-5',    'Winamac'),
(138,71,  'America/Kentucky/Louisville',       'UTC-5',    'Louisville, Jeffersonville, New Albany, Jeffersontown, Pleasure Ridge Park'),
(139,71,  'America/Kentucky/Monticello',       'UTC-5',    'Monticello'),
(140,71,  'America/New_York',                  'UTC-5',    'New York City, Brooklyn, Borough of Queens, Philadelphia, Manhattan'),
(141,72,  'Grenade',                           'UTC-5',    'Grenade'),
(142,73,  'America/Guatemala',                 'UTC-5',    'Guatemala City, Mixco, Villa Nueva, Petapa, San Juan Sacatepéquez'),
(143,74,  'America/Guyana',                    'UTC-4',    'Georgetown, Linden, New Amsterdam, Anna Regina, Bartica'),
(144,75,  'America/Port-au-Prince',            'UTC-5',    'Port-au-Prince, Carrefour, Delmas 73, Pétionville, Port-de-Paix'),
(145,76,  'America/Tegucigalpa',               'UTC-6',    'Tegucigalpa, San Pedro Sula, Choloma, La Ceiba, El Progreso'),
(146,77,  'America/Jamaica',                   'UTC-6',    'Kingston, New Kingston, Spanish Town, Portmore, Montego Bay'),
(147,78,  'America/Tijuana',                   'UTC-8',    'Tijuana, Mexicali, Ensenada, Rosarito, Tecate'),
(148,78,  'America/Chihuahua',                 'UTC-7',    'Chihuahua, Ciudad Delicias, Hidalgo del Parral, Cuauhtémoc, Nuevo Casas Grandes'),
(149,78,  'America/Hermosillo',                'UTC-7',    'Hermosillo, Ciudad Obregón, Nogales, San Luis Río Colorado, Navojoa'),
(150,78,  'America/Mazatlan',                  'UTC-7',    'Culiacán, Mazatlán, Tepic, Los Mochis, La Paz'),
(151,78,  'America/Ojinaga',                   'UTC-7',    'Ciudad Juárez, Manuel Ojinaga, Ojinaga'),
(152,78,  'America/Bahia_Banderas',            'UTC-6',    'Bucerías, Valle de Banderas'),
(153,78,  'America/Matamoros',                 'UTC-6',    'Reynosa, Heroica Matamoros, Nuevo Laredo, Piedras Negras, Ciudad Acuña'),
(154,78,  'America/Merida',                    'UTC-6',    'Mérida, Campeche, Ciudad del Carmen, Kanasín, Progreso de Castro'),
(155,78,  'America/Mexico_City',               'UTC-6',    'Mexico City, Iztapalapa, Ecatepec, Guadalajara, Puebla'),
(156,78,  'America/Monterrey',                 'UTC-6',    'Gustavo A. Madero, Monterrey, Guadalupe, Saltillo, Torreon'),
(157,78,  'America/Cancun',                    'UTC-5',    'Cancún, Chetumal, Playa del Carmen, San Miguel de Cozumel, Felipe Carrillo Puerto'),
(158,79,  'America/Managua',                   'UTC-5',    'Managua, León, Masaya, Tipitapa, Chinandega'),
(159,80,  'America/Panama',                    'UTC-5',    'Panamá, San Miguelito, Tocumen, David, Arraiján'),
(160,81,  'America/Asuncion',                  'UTC-5',    'Asunción, Ciudad del Este, San Lorenzo, Capiatá, Lambaré'),
(161,82,  'America/Lima',                      'UTC-5',    'Lima, Arequipa, Callao, Trujillo, Chiclayo'),
(162,83,  'America/St_Kitts',                  'UTC-4',    'Basseterre, Fig Tree, Market Shop, Saint Paul’s, Middle Island'),
(163,84,  'America/St_Lucia',                  'UTC-4',    'Castries, Bisée, Vieux Fort, Micoud, Soufrière'),
(164,85,  'America/St_Vincent',                'UTC-4',    'Kingstown, Kingstown Park, Georgetown, Barrouallie, Port Elizabeth'),
(165,86,  'America/El_Salvador',               'UTC-4',    'San Salvador, Soyapango, Santa Ana, San Miguel, Mejicanos'),
(166,87,  'America/Paramaribo',                'UTC-3',    'Paramaribo, Lelydorp, Brokopondo, Nieuw Nickerie, Moengo'),
(167,88,  'America/Port_of_Spain',             'UTC-3',    'Laventille, Chaguanas, Mon Repos, San Fernando, Port of Spain'),
(168,89,  'America/Montevideo',                'UTC-3',    'Montevideo, Salto, Paysandú, Las Piedras, Rivera'),
(169,90,  'America/Caracas',                   'UTC-3',    'Caracas, Maracaibo, Maracay, Valencia, Barquisimeto'),
(170,91,  'Asia/Kabul',                        'UTC+4:30', 'Kabul, Kandahār, Mazār-e Sharīf, Herāt, Jalālābād'),
(171,92,  'Asia/Riyadh',                       'UTC-3',    'Riyadh, Jeddah, Mecca, Medina, Sulţānah'),
(172,93,  'Asia/Yerevan',                      'UTC+4',    'Yerevan, Gyumri, Vanadzor, Ejmiatsin, Hrazdan'),
(173,94,  'Asia/Baku',                         'UTC+4',    'Baku, Ganja, Sumqayıt, Lankaran, Mingelchaur'),
(174,95,  'Asia/Bahrain',                      'UTC+3',    'Manama, Al Muharraq, Ar Rifā‘, Dār Kulayb, Madīnat Ḩamad'),
(175,96,  'Asia/Dhaka',                        'UTC+6',    'Dhaka, Chittagong, Khulna, Rājshāhi, Comilla'),
(176,97,  'Asia/Thimphu',                      'UTC+6',    'Thimphu, Punākha, Tsirang, Phuntsholing, Pemagatshel'),
(177,98,  'Birmanie',                       'Burma'),
(178,99,  'Asia/Brunei',                       'UTC+8',    'Bandar Seri Begawan, Kuala Belait, Seria, Tutong, Bangar'),
(179,100,'Asia/Phnom_Penh',                    'UTC+7',    'Phnom Penh, Takeo, Sihanoukville, Battambang, Siem Reap'),
(180,101,'Asia/Urumqi',                        'UTC+6',    'Zhongshan, Ürümqi, Zhanjiang, Shihezi, Turpan'),
(181,101,'Asia/Shanghai',                      'UTC+8',    'Shanghai, Beijing, Tianjin, Guangzhou, Shenzhen'),
(181,102,'Asia/Famagusta',                     'UTC+2',    'Famagusta'),
(182,103,'Asia/Pyongyang',                     'UTC+9',    'Pyongyang, Hamhŭng, Namp’o, Hŭngnam, Kaesŏng'),
(183,104,'Asia/Seoul',                         'UTC+9',    'Seoul, Busan, Incheon, Daegu, Daejeon'),
(184,105,'Asia/Dubai',                         'UTC+4',    'Dubai, Abu Dhabi, Sharjah, Al Ain, Ajman'),
(185,106,'Asia/Tbilisi',                       'UTC+4',    'Tbilisi, Kutaisi, Batumi, Sokhumi, Zugdidi'),
(186,107,'Asia/Kolkata',                       'UTC+5:30', 'Mumbai, Delhi, Bengaluru, Kolkata, Chennai'),
(187,108,'Asia/Jakarta',                       'UTC+7',    'Jakarta, Surabaya, Medan, Bandung, Bekasi'),
(188,108,'Asia/Pontianak',                     'UTC+7',    'Pontianak, Tanjungpinang, Palangkaraya, Singkawang, Sampit'),
(189,108,'Asia/Makassar',                      'UTC+8',    'Makassar, Denpasar, City of Balikpapan, Banjarmasin, Manado'),
(190,108,'Asia/Jayapura',                      'UTC+9',    'Ambon, Jayapura, Sorong, Ternate, Abepura'),
(191,109,'Asia/Baghdad',                       'UTC+3',    'Baghdad, Basrah, Al Mawşil al Jadīdah, Al Başrah al Qadīmah, Mosul'),
(192,110,'Asia/Tehran',                        'UTC+5:30', 'Tehran, Mashhad, Isfahan, Karaj, Tabriz'),
(193,111,'Asia/Jerusalem',                     'UTC+3',    'Jerusalem, West Jerusalem, Haifa, Tel Aviv, Ashdod'),
(194,112,'Asia/Tokyo',                         'UTC+9',    'Tokyo, Yokohama, Osaka, Nagoya, Sapporo'),
(195,113,'Asia/Amman',                         'UTC+2',    'Amman, Zarqa, Irbid, Russeifa, Wādī as Sīr'),
(196,114,'Asia/Aqtau',                         'UTC+5',    'Aktau, Zhanaozen, Beyneu, Shetpe, Yeraliyev'),
(197,114,'Asia/Aqtobe',                        'UTC+5',    'Aqtöbe, Kandyagash, Shalqar, Khromtau, Embi'),
(198,114,'Asia/Atyrau',                        'UTC+5',    'Atyrau'),
(199,114,'Asia/Oral',                          'UTC+5',    'Oral, Atyrau, Qulsary, Aqsay, Shalkar'),
(200,114,'Asia/Qyzylorda',                     'UTC+5',    'Kyzylorda, Kostanay, Rudnyy, Dzhetygara, Lisakovsk'),
(201,114,'Asia/Almaty',                        'UTC+6',    'Almaty, Karagandy, Shymkent, Taraz, Astana'),
(202,114,'Asia/Qostanay',                      'UTC+6',    'Qostanay'),
(203,115,'Asia/Bishkek',                       'UTC+6',    'Bishkek, Osh City, Osh, Jalal-Abad, Karakol'),
(204,116,'Asia/Kuwait',                        'UTC+3',    'Al Aḩmadī, Ḩawallī, As Sālimīyah, Şabāḩ as Sālim, Al Farwānīyah'),
(205,117,'Asia/Vientiane',                     'UTC+7',    'Vientiane, Pakse, Savannakhét, Luang Prabang, Xam Nua'),
(206,118,'Asia/Beirut',                        'UTC+2',    'Beirut, Ra’s Bayrūt, Tripoli, Sidon, Tyre'),
(207,119,'Asia/Kuala_Lumpur',                  'UTC+8',    'Kota Bharu, Kuala Lumpur, Klang, Kampung Baru Subang, Johor Bahru'),
(208,120,'Indian/Maldives',                    'UTC+5',    'Male, Fuvahmulah, Hithadhoo, Kulhudhuffushi, Thinadhoo'),
(209,121,'Asia/Hovd',                          'UTC+7',    'Khovd, Ölgiy, Ulaangom, Uliastay, Altai'),
(210,122,'Asia/Kathmandu',                     'UTC+5:45', 'Kathmandu, Pokhara, Pātan, Biratnagar, Bīrganj'),
(211,123,'Asia/Muscat',                        'UTC+4',    'Muscat, Seeb, Şalālah, Bawshar, Sohar'),
(212,124,'Asia/Samarkand',                     'UTC+5',    'Samarqand, Bukhara, Nukus, Qarshi, Jizzax'),
(213,124,'Asia/Tashkent',                      'UTC+5',    'Tashkent, Namangan, Andijon, Qo‘qon, Chirchiq'),
(214,125,'Asia/Karachi',                       'UTC+5',    'Karachi, Lahore, Faisalābād, Rawalpindi, Multān'),
(215,126,'Asia/Manila',                        'UTC+8',    'Quezon City, Manila, Budta, Davao, Malingao'),
(216,127,'Asia/Qatar',                         'UTC+3',    'Doha, Ar Rayyān, Umm Şalāl Muḩammad, Al Wakrah, Al Khawr'),
(217,128,'Asia/Singapore',                     'UTC+8',    'Singapore'),
(218,129,'Asia/Colombo',                       'UTC+5:30', 'Colombo, Dehiwala-Mount Lavinia, Mount Lavinia, Galkissa, Moratuwa'),
(219,130,'Asia/Damascus',                      'UTC+2',    'Aleppo, Damascus, Homs, Ḩamāh, Latakia'),
(220,131,'Asia/Dushanbe',                      'UTC+5',    'Dushanbe, Khŭjand, Kŭlob, Qŭrghonteppa, Istaravshan'),
(221,132,'Asia/Bangkok',                       'UTC+7',    'Bangkok, Samut Prakan, Mueang Nonthaburi, Udon Thani, Chon Buri'),
(222,133,'Asia/Dili',                          'UTC+7',    'Dili, Same, Maliana, Suai, Liquica'),
(223,134,'Asia/Ashgabat',                      'UTC+5',    'Ashgabat, Türkmenabat, Daşoguz, Mary, Balkanabat'),
(224,135,'Europe/Istanbul',                    'UTC+3',    'İstanbul, Ankara, İzmir, Bursa, Adana'),
(225,136,'Asia/Ho_Chi_Minh',                   'UTC+7',    'Ho Chi Minh City, Hanoi, Da Nang, Haiphong, Biên Hòa'),
(226,137,'Europe/Tirane',                      'UTC+7',    'Tirana, Durrës, Elbasan, Vlorë, Shkodër'),
(227,138,'Europe/Berlin',                      'UTC+1',    'Berlin, Hamburg, München, Köln, Frankfurt am Main'),
(228,139,'Europe/Andorra',                     'UTC+1',    'Andorra la Vella, les Escaldes, Encamp, Sant Julià de Lòria, la Massana'),
(229,140,'Europe/Vienna',                      'UTC+1',    'Vienna, Graz, Linz, Salzburg, Innsbruck'),
(230,141,'Europe/Brussels',                    'UTC+1',    'Brussels, Antwerpen, Gent, Charleroi, Liège'),
(231,142,'Europe/Minsk' ,                      'UTC+3',    'Minsk, Gomel, Mahilyow, Vitebsk, Hrodna'),
(232,143,'Europe/Sarajevo',                    'UTC+1',    'Sarajevo, Banja Luka, Zenica, Tuzla, Mostar'),
(233,144,'Europe/Sofia',                       'UTC+2',    'Sofia, Plovdiv, Varna, Burgas, Ruse'),
(234,145,'Asia/Famagusta',                     'UTC+2',    'Famagusta'),
(235,146,'Crete'                          , 'Crest'),
(226,147,'Europe/Zagreb',                      'UTC+2',    'Zagreb - Centar, Zagreb, Split, Rijeka, Osijek'),
(227,148,'Europe/Copenhagen',                  'UTC+1',    'Copenhagen, Århus, Odense, Aalborg, Frederiksberg'),
(228,149,'Atlantic/Canary',                    'UTC+0',    'Las Palmas de Gran Canaria, Santa Cruz de Tenerife, La Laguna, Telde, Arona'),
(229,149,'Africa/Ceuta',                       'UTC+1',    'Ceuta, Melilla'),
(230,149,'Europe/Madrid',                      'UTC+1',    'Madrid, Barcelona, Valencia, Sevilla, Zaragoza'),
(231,150,'Europe/Tallinn',                     'UTC+2',    'Tallinn, Tartu, Narva, Kohtla-Järve, Pärnu'),
(232,151,'Europe/Helsinki',                    'UTC+2',    'Helsinki, Espoo, Tampere, Vantaa, Turku'),
(233,152,'Europe/Paris',                       'UTC+1',    'Paris, Marseille, Lyon, Toulouse, Nice'),
(234,153,'Europe/Athens',                      'UTC+2',    'Athens, Thessaloníki, Pátra, Piraeus, Lárisa'),
(235,154,'Europe/Budapest',                    'UTC+2',    'Budapest, Debrecen, Miskolc, Szeged, Pécs'),
(236,155,'Europe/Dublin',                      'UTC+1',    'Dublin, Cork, Dún Laoghaire, Luimneach, Gaillimh'),
(237,156,'Atlantic/Reykjavik',                 'UTC+0',    'Reykjavík, Kópavogur, Hafnarfjörður, Akureyri, Garðabær'),
(238,157,'Europe/Rome',                        'UTC+1',    'Rome, Milano, Napoli, Turin, Palermo'),
(239,158,'Europe/Riga',                        'UTC+2',    'Riga, Daugavpils, Vec-Liepāja, Liepāja, Jelgava'),
(240,159,'Europe/Vaduz',                       'UTC+1',    'Schaan, Vaduz, Triesen, Balzers, Eschen'),
(241,160,'Europe/Vilnius',                     'UTC+2',    'Vilnius, Kaunas, Klaipėda, Šiauliai, Panevėžys'),
(242,161,'Europe/Luxembourg',                  'UTC+1',    'Luxembourg, Esch-sur-Alzette, Dudelange, Schifflange, Bettembourg'),
(243,162,'Europe/Skopje',                      'UTC+1',    'Skopje, Bitola, Kumanovo, Prilep, Tetovo'),
(244,163,'Europe/Malta',                       'UTC+1',    'Birkirkara, Qormi, Mosta, Żabbar, San Pawl il-Baħar'),
(245,164,'Europe/Chisinau',                    'UTC+2',    'Chişinău, Tiraspolul, Bălţi, Bender, Rîbniţa'),
(246,165,'Europe/Monaco',                      'UTC+1',    'Monaco, Monte-Carlo, La Condamine'),
(247,166,'Europe/Podgorica',                   'UTC+1',    'Podgorica, Nikšić, Herceg-Novi, Pljevlja, Budva'),
(248,167,'Europe/Oslo',                        'UTC+1',    'Oslo, Bergen, Trondheim, Stavanger, Drammen'),
(249,168,'Europe/Amsterdam',                   'UTC+1',    'Amsterdam, Rotterdam, The Hague, Utrecht, Eindhoven'),
(250,169,'Europe/Warsaw',                      'UTC+1',    'Warsaw, Łódź, Kraków, Wrocław, Poznań'),
(251,170,'Atlantic/Azores',                    'UTC-1',    'Ponta Delgada, Angra do Heroísmo, Lagoa, Rosto de Cão, Rabo de Peixe'),
(252,171,'Europe/Prague',                      'UTC+1',    'Prague, Brno, Ostrava, Pilsen, Olomouc'),
(253,172,'Europe/Bucharest',                   'UTC+2',    'Bucharest, Sector 3, Sector 6, Sector 2, Iaşi'),
(254,173,'Europe/London',                      'UTC+0',    'London, City of London, Birmingham, Glasgow, Liverpool'),
(255,174,'Europe/Kaliningrad',                 'UTC+2',    'Kaliningrad, Chernyakhovsk, Sovetsk, Baltiysk, Gusev'),
(256,174,'Europe/Kirov',                       'UTC+3',    'Kirov'),
(257,174,'Europe/Moscow',                      'UTC+3',    'Moscow, Saint Petersburg, Nizhniy Novgorod, Kazan, Rostov-na-Donu'),
(258,174,'Europe/Simferopol',                  'UTC+3',    'Sevastopol, Simferopol, Kerch, Yevpatoriya, Yalta'),
(259,174,'Europe/Astrakhan',                   'UTC+4',    'Astrakhan, Akhtubinsk, Znamensk, Kharabali, Kamyzyak'),
(260,174,'Europe/Samara',                      'UTC+4',    'Samara, Tol’yatti, Izhevsk, Syzran’, Novokuybyshevsk'),
(261,174,'Europe/Saratov',                     'UTC+4',    'Saratov'),
(262,174,'Europe/Ulyanovsk',                   'UTC+4',    'Ulyanovsk'),
(263,174,'Europe/Volgograd',                   'UTC+4',    'Volgograd, Saratov, Kirov, Volzhskiy, Balakovo'),
(264,174,'Asia/Yekaterinburg',                 'UTC+5',    'Yekaterinburg, Chelyabinsk, Ufa, Perm, Orenburg'),
(265,174,'Asia/Omsk',                          'UTC+6',    'Omsk, Biysk, Rubtsovsk, Novoaltaysk, Gorno-Altaysk'),
(266,174,'Asia/Barnaul',                       'UTC+7',    'Barnaul'),
(267,174,'Asia/Krasnoyarsk',                   'UTC+7',    'Krasnoyarsk, Abakan, Norilsk, Achinsk, Kyzyl'),
(268,174,'Asia/Novokuznetsk',                  'UTC+7',    'Novokuznetsk, Kemerovo, Prokop’yevsk, Leninsk-Kuznetsky, Kiselëvsk'),
(269,174,'Asia/Novosibirsk',                   'UTC+7',    'Novosibirsk, Tomsk, Seversk, Berdsk, Iskitim'),
(270,174,'Asia/Tomsk',                         'UTC+7',    'Tomsk'),
(271,174,'Asia/Irkutsk',                       'UTC+8',    'Irkutsk, Ulan-Ude, Bratsk, Angarsk, Ust’-Ilimsk'),
(272,174,'Asia/Chita',                         'UTC+9',    'Chita'),
(273,174,'Asia/Khandyga',                      'UTC+9',    'Khandyga'),
(274,174,'Asia/Yakutsk',                       'UTC+9',    'Chita, Yakutsk, Blagoveshchensk, Belogorsk, Neryungri'),
(275,174,'Asia/Ust-Nera',                      'UTC+9',    'Ust-Nera'),
(276,174,'Asia/Vladivostok',                   'UTC+10',    'Vladivostok, Khabarovsk, Khabarovsk Vtoroy, Komsomolsk-on-Amur, Ussuriysk'),
(277,174,'Asia/Magadan',                       'UTC+11',    'Magadan, Ust-Nera, Susuman, Ola'),
(278,174,'Asia/Sakhalin',                      'UTC+11',    'Yuzhno-Sakhalinsk, Korsakov, Kholmsk, Okha, Nevel’sk'),
(279,174,'Asia/Srednekolymsk',                 'UTC+11',    'Srednekolymsk'),
(279,174,'Asia/Anadyr',                        'UTC+12',    'Anadyr, Bilibino'),
(280,174,'Asia/Kamchatka',                     'UTC+12',    'Petropavlovsk-Kamchatsky, Yelizovo, Vilyuchinsk, Klyuchi'),
(281,175,'Europe/San_Marino',                  'UTC+1',     'Serravalle, Borgo Maggiore, San Marino, Domagnano, Fiorentino'),
(282,176,'Europe/Belgrade',                    'UTC+1',     'Belgrade, Pristina, Niš, Novi Sad, Prizren"'),
(283,177,'Europe/Bratislava',                  'UTC+1',     'Bratislava, Košice, Prešov, Nitra, Žilina'),
(284,178,'Europe/Ljubljana',                   'UTC+1',     'Ljubljana, Maribor, Celje, Kranj, Velenje'),
(285,179,'Europe/Stockholm',                   'UTC+1',     'Stockholm, Göteborg, Malmö, Uppsala, Västerås'),
(286,180,'Suisse'                         , 'Swiss'),
(287,181,'Europe/Kiev',                        'UTC+2',     'Kiev, Kharkiv, Dnipropetrovsk, Donetsk, Odessa'),
(288,181,'Europe/Uzhgorod',                    'UTC+2',     'Uzhhorod, Mukacheve, Khust, Vynohradiv, Berehove'),
(289,181,'Europe/Zaporozhye',                  'UTC+2',     'Zaporizhzhya, Luhansk, Melitopol’, Syevyerodonets’k, Berdyans’k'),
(290,182,'Europe/Vatican',                     'UTC+1',     'Vatican City'),
(291,183,'Australia/Perth',                    'UTC+8',     'Perth, Rockingham, Mandurah, Bunbury, Armadale'),
(292,183,'Australia/Eucla',                    'UTC+8:45',  'Eucla'),
(293,183,'Australia/Adelaide',                 'UTC+9:30',  'Adelaide, Adelaide Hills, Mount Gambier, Morphett Vale, Prospect'),
(294,183,'Australia/Broken_Hill',              'UTC+9:30',  'Broken Hill'),
(295,183,'Australia/Darwin',                   'UTC+9:30',  'Darwin, Alice Springs, Palmerston, Katherine, McMinns Lagoon'),
(296,183,'Australia/Brisbane',                 'UTC+10',    'Brisbane, Gold Coast, Logan City, Townsville, Cairns'),
(297,183,'Australia/Currie',                   'UTC+10',    'Currie'),
(298,183,'Australia/Hobart',                   'UTC+10',    'Hobart, Launceston, Burnie, Devonport, Kingston'),
(299,183,'Australia/Lindeman',                 'UTC+10',    'Lindeman'),
(300,183,'Australia/Melbourne',                'UTC+10',    'Melbourne, Geelong, Bendigo, Ballarat, Reservoir'),
(301,183,'Australia/Sydney',                   'UTC+10',    'Sydney, Canberra, Newcastle, Wollongong, Maitland'),
(302,183,'Australia/Lord_Howe',                'UTC+10:30', 'Lord Howe'),
(303,183,'Antarctica/Macquarie',               'UTC+11',    'Macquarie'),
(304,184,'Pacific/Rarotonga',                  'UTC+10',    'Avarua'),
(305,185,'Pacific/Fiji',                       'UTC+12',    'FijiSuva, Lautoka, Nadi, Labasa, Ba'),
(306,186,'Pacific/Tarawa',                     'UTC+12',    'Tarawa, Betio Village, Bikenibeu Village'),
(307,186,'Pacific/Enderbury',                  'UTC+13',    'Enderbury'),
(308,186,'Pacific/Kiritimati',                 'UTC+14',    'Kiritimati'),
(309,187,'Pacific/Kwajalein',                  'UTC+12',    'Ebaye, Jabat'),
(310,187,'Pacific/Majuro',                     'UTC+12',    'Majuro, Arno, Jabor, Wotje, Mili'),
(311,188,'Pacific/Chuuk',                      'UTC+10',    'Weno Town, Colonia'),
(312,188,'Pacific/Kosra',                      'UTC+11',    'Tofol'),
(313,188,'Pacific/Pohnpei',                    'UTC+11',    'Kolonia, Kolonia Town, Palikir - National Government Center'),
(314,189,'Pacific/Nauru',                      'UTC+12',    'Yaren, Baiti, Anabar, Uaboe, Ijuw'),
(315,190,'Pacific/Niue',                       'UTC-11',    'Alofi'),
(316,191,'Pacific/Auckland',                   'UTC+12',    'Auckland, Wellington, Christchurch, Manukau City, Waitakere'),
(317,191,'Pacific/Chatham',                    'UTC+12:45', 'Waitangi'),
(318,192,'Pacific/Palau',                      'UTC+9',     'Koror, Koror Town, Kloulklubed, Ulimang, Mengellang'),
(319,193,'Pacific/Port_Moresby',               'UTC+10',    'Port Moresby, Lae, Mount Hagen, Popondetta, Madang'),
(320,193,'Pacific/Bougainville',               'UTC+11',    'Arawa, Buka'),
(321,194,'Pacific/Guadalcanal',                'UTC+11',    'Honiara, Auki, Gizo, Buala, Tulaghi'),
(322,195,'Pacific/Apia',                       'UTC+11',    'Apia, Asau, Mulifanua, Leulumoega, Lufilufi'),
(323,196,'Pacific/Tongatapu',                  'UTC+13',    'Nuku‘alofa, Neiafu, Pangai, ‘Ohonua, Hihifo'),
(324,197,'Pacific/Funafuti',                   'UTC+12',    'Funafuti, Savave Village, Tanrake Village, Toga Village, Asau Village'),
(325,198,'Pacific/Efate',                      'UTC+11',    'Port-Vila, Luganville, Isangel, Sola, Lakatoro');

















